//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FortuneTellerMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rube
    {
        public int RubeID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int ColorListID { get; set; }
        public int BirthMonthID { get; set; }
        public int Age { get; set; }
    
        public virtual BirthMonth BirthMonth { get; set; }
        public virtual ColorList ColorList { get; set; }
    }
}
